# Generated by Django 3.2.16 on 2022-12-21 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='The best company', max_length=50)),
                ('phone_number', models.CharField(default='+91 999 999 9999', max_length=20)),
                ('address', models.CharField(default='default address', max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='settings/', validators=[projects.models.file_size])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
