# Generated by Django 3.2.16 on 2022-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=50),
        ),
    ]
