# Generated by Django 3.2.16 on 2022-12-21 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_appsettings_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='email',
            field=models.CharField(default='abc@example.com', max_length=30, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
