# Generated by Django 3.2.16 on 2022-12-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_appsettings_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='website',
            field=models.CharField(default='www.example.com', max_length=50),
        ),
    ]
