# Generated by Django 3.2.16 on 2022-12-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
