# Generated by Django 3.2.16 on 2022-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20221226_2319'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('title', 'text', 'user', 'viewed_at'), name='notifications_notification_unique'),
        ),
    ]
