# Generated by Django 3.2.16 on 2022-11-28 16:04

from django.db import migrations, models
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20221128_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='material/', validators=[projects.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='low_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='MaterialImage',
        ),
    ]
