# Generated by Django 3.2.16 on 2022-11-28 16:08

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20221128_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(null=True, upload_to='material/', validators=[projects.models.file_size]),
        ),
    ]
