# Generated by Django 3.2.16 on 2022-11-28 16:10

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, upload_to='material/', validators=[projects.models.file_size]),
        ),
    ]
