# Generated by Django 3.2.16 on 2022-11-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_inventoryadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='low_level',
        ),
        migrations.AddField(
            model_name='inventory',
            name='low_level',
            field=models.IntegerField(default=10),
        ),
    ]
