# Generated by Django 3.2.16 on 2022-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_materialqty_materialqtytransfer_materialtransfer_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialqty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
