# Generated by Django 3.2.16 on 2022-12-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_materialreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreturn',
            name='destination',
        ),
    ]
