# Generated by Django 3.2.16 on 2022-12-12 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_remove_materialreturn_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
