# Generated by Django 3.2.16 on 2022-12-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_auto_20221214_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='units',
            new_name='unit',
        ),
    ]
