# Generated by Django 3.2.16 on 2022-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_rename_units_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='notes',
            field=models.CharField(default='', max_length=30),
        ),
    ]
