# Generated by Django 3.2.16 on 2023-02-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20230102_1649'),
        ('materials', '0019_auto_20230102_1752'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='uniq_inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('material_id', 'warehouse_id', 'owner_id'), name='uniq_inventory'),
        ),
    ]
