# Generated by Django 3.2.16 on 2023-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20230207_1337'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='uniq_inventory',
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('material_id', 'warehouse_id', 'owner_id'), name='uniq_owner_inventory'),
        ),
    ]
