# Generated by Django 4.1.2 on 2022-11-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='designation',
            field=models.CharField(default='Manager', max_length=10),
        ),
    ]
