# Generated by Django 4.1.2 on 2022-11-23 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientcontact_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
