# Generated by Django 3.2.16 on 2022-12-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientcontact_created_at_clientcontact_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
