# Generated by Django 3.2.16 on 2023-01-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20221214_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
