# Generated by Django 3.2.16 on 2022-12-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecat',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
