# Generated by Django 3.2.16 on 2022-11-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttimeline',
            old_name='deal',
            new_name='project',
        ),
    ]
