# Generated by Django 3.2.16 on 2022-11-25 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
