# Generated by Django 3.2.16 on 2022-11-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectfiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttimeline',
            name='project_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectfiles'),
        ),
    ]
