# Generated by Django 3.2.16 on 2022-11-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projecttimeline_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='notes',
            field=models.CharField(max_length=50),
        ),
    ]
