# Generated by Django 3.2.16 on 2022-11-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projecttimeline_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimeline',
            name='project_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfiles'),
        ),
    ]
