# Generated by Django 3.2.16 on 2022-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientcontact_created_at_clientcontact_updated_at'),
        ('projects', '0009_alter_projecttimeline_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='project',
            name='contact_person',
            field=models.ManyToManyField(to='clients.ClientContact'),
        ),
    ]
