# Generated by Django 3.2.16 on 2022-12-14 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20221214_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deliveryChallan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.deliverychallan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.product')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryProducts',
        ),
    ]
