# Generated by Django 3.2.16 on 2022-12-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20221214_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='vehicleNo',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttimeline',
            name='type',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
        ),
    ]
