# Generated by Django 3.2.16 on 2022-12-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20221216_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReturn',
        ),
    ]
