# Generated by Django 3.2.16 on 2022-12-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_productreturn_returns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returns',
            name='challanNo',
        ),
        migrations.AddField(
            model_name='returns',
            name='challan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.deliverychallan'),
            preserve_default=False,
        ),
    ]
