# Generated by Django 3.2.16 on 2022-12-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20221219_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryproduct',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
