# Generated by Django 3.2.16 on 2022-12-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20221220_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returns',
            name='description',
        ),
    ]
