# Generated by Django 3.2.16 on 2022-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_imchallan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_rank',
            field=models.IntegerField(default=0),
        ),
    ]
